# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QueryRasterFromPoint
                                 A QGIS plugin
 Query raster layer values from point vector layer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-11-16
        copyright            : (C) 2020 by Damián Ortega Terol
        email                : dortegat@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """
    Load QueryRasterFromPoint class from file QueryRasterFromPoint.
    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    from .query_raster_from_point import QueryRasterFromPoint
    return QueryRasterFromPoint(iface)